#!/usr/bin/env python3
"""Build speaker_text.tex from the \\note{...} of every active frame in main.tex.

The note text is not duplicated anywhere: main.tex stays the single source.
Usage: python3 tools/extract_notes.py [main.tex] [speaker_text.tex]

Output: article, 12 pt, one page per frame, header "N / 21  Frame title"
(backup frames "B1", "B2", ...), one short paragraph per spoken sentence,
bracketed asides ([optional: ...], [if asked: ...], [two time constants: ...]) in muted gray, per-frame word
count, and on the first page the total spoken words and read-aloud time at
130 words per minute. Words inside bracketed asides are not counted as
spoken.
"""
import re
import sys

WPM = 130
src = sys.argv[1] if len(sys.argv) > 1 else "main.tex"
dst = sys.argv[2] if len(sys.argv) > 2 else "speaker_text.tex"


def strip_comments(text):
    """Remove LaTeX comments (unescaped % to end of line)."""
    return "\n".join(re.sub(r"(?<!\\)%.*$", "", line) for line in text.split("\n"))


def braced(text, i):
    """text[i] == '{'; return (content, index after the closing brace)."""
    assert text[i] == "{"
    depth, j = 0, i
    while j < len(text):
        c = text[j]
        if c == "\\":
            j += 2
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[i + 1:j], j + 1
        j += 1
    raise ValueError("unbalanced braces at %d" % i)


def plain_words(latex):
    """Approximate spoken word count of a LaTeX fragment."""
    t = re.sub(r"\\[a-zA-Z]+\*?", " ", latex)
    t = re.sub(r"[{}$\\~]", " ", t)
    return len(re.findall(r"[A-Za-z0-9][\w'\-\.,]*", t))


# any bracketed block that starts with a lowercase word, e.g. [optional: ...],
# [if asked: ...], [two time constants: ...]
ASIDE = re.compile(r"\[[a-z][^\]]*\]")


def split_note(note):
    """Return list of (kind, latex): kind 'say' for spoken sentences, 'aside' for brackets."""
    # unwrap \qa{...} (main.tex macro that sets asides small and muted on the notes page)
    while "\\qa{" in note:
        k = note.index("\\qa{")
        inner, after = braced(note, k + 3)
        note = note[:k] + " " + inner + " " + note[after:]
    parts, last = [], 0
    for m in ASIDE.finditer(note):
        parts.append(("say", note[last:m.start()]))
        parts.append(("aside", m.group(0)))
        last = m.end()
    parts.append(("say", note[last:]))
    out = []
    for kind, txt in parts:
        txt = " ".join(txt.split())
        if not txt:
            continue
        if kind == "aside":
            out.append((kind, txt))
            continue
        # one paragraph per spoken sentence
        for s in re.split(r"(?<=[.?!])\s+(?=[A-Z0-9])", txt):
            if s.strip():
                out.append(("say", s.strip()))
    return out


text = strip_comments(open(src, encoding="utf-8").read())
title_m = re.search(r"\\title\{", text)
deck_title = braced(text, title_m.end() - 1)[0] if title_m else "Title"
appendix_at = text.find("\\appendix")

frames = []
for m in re.finditer(r"\\begin\{frame\}", text):
    i = m.end()
    if text.startswith("[", i):          # frame options, e.g. [t]
        i = text.index("]", i) + 1
    title = braced(text, i)[0] if text.startswith("{", i) else deck_title
    end = text.index("\\end{frame}", i)
    n = text.find("\\note{", i, end)
    note = braced(text, n + 5)[0] if n >= 0 else ""
    backup = appendix_at >= 0 and m.start() > appendix_at
    frames.append((title, note, backup))

nmain = sum(1 for f in frames if not f[2])
rows, pages, total, k_main, k_bak = [], [], 0, 0, 0
for title, note, backup in frames:
    if backup:
        k_bak += 1
        label = "B%d" % k_bak
    else:
        k_main += 1
        label = "%d / %d" % (k_main, nmain)
    parts = split_note(note)
    words = sum(plain_words(t) for kind, t in parts if kind == "say")
    if not backup:
        total += words
    rows.append("%s & %s & %d\\\\" % (label, title, words))
    body = []
    for kind, t in parts:
        if kind == "aside":
            body.append("{\\color{aside}\\small %s\\par}" % t)
        else:
            body.append(t + "\\par")
    pages.append(
        "\\newpage\n\\noindent{\\large\\bfseries %s\\quad %s}\\hfill"
        "{\\color{aside}\\small %d words}\\par\\medskip\\hrule\\bigskip\n%s\n"
        % (label, title, words, "\n".join(body)))

minutes = total / WPM
doc = r"""%% Generated by tools/extract_notes.py from %(src)s; do not edit by hand.
\documentclass[12pt]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage[a4paper,margin=2.2cm]{geometry}
\usepackage{xcolor}
\usepackage{longtable}
\definecolor{aside}{gray}{0.45}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0.7em}
\linespread{1.25}
\raggedright
\pagestyle{empty}
\begin{document}
{\Large\bfseries Speaker text: %(title)s}\par
MeVArc 2026, Montreux, Monday 5 October 2026, 12:00\par
\medskip
Spoken words, %(n)d main frames: \textbf{%(total)d}; read aloud at %(wpm)d words per minute:
\textbf{%(min).1f\,min}. Gray text in brackets is optional or for questions only and is not counted.
\par\medskip
{\small
\begin{longtable}{@{}l p{11.5cm} r@{}}
Frame & Title & Words\\ \hline
%(rows)s
\end{longtable}}
%(pages)s
\end{document}
""" % dict(src=src, title=deck_title, n=nmain, total=total, wpm=WPM, min=minutes,
           rows="\n".join(rows), pages="\n".join(pages))
open(dst, "w", encoding="utf-8").write(doc)
print("%s: %d frames (%d main), %d spoken words, %.1f min at %d wpm"
      % (dst, len(frames), nmain, total, minutes, WPM))
